###ADD TO CART
POST http://localhost:3000/api/cart/add
Content-Type: application/json

{
    "userId":"b081df4b-3b52-4cb0-9340-d1ca02901291",
    "productId":"1c28684c-3849-42c7-844f-b74fb56f9b12",
    "quantity": 12
}

###GET CART ITEM
GET http://localhost:3000/api/cart/22e69b45-3dc9-46bb-ae17-009d0f4c2a02

###UPDATE CART ITEMS
PUT http://localhost:3000/api/cart/update
Content-Type: application/json

{
    "userId":"22e69b45-3dc9-46bb-ae17-009d0f4c2a02",
    "productId":"1c28684c-3849-42c7-844f-b74fb56f9b12",
    "newQuantity": 2
}

###GET ALL CART ITEMS
GET http://localhost:3000/api/cart/all/b081df4b-3b52-4cb0-9340-d1ca02901291

###REMOVE ITEMS FROM CART
POST http://localhost:3000/api/cart/remove
Content-Type: application/json

{
    "userId":"b081df4b-3b52-4cb0-9340-d1ca02901291",
    "productId":"1c28684c-3849-42c7-844f-b74fb56f9b12"
}